sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "Doxyy8WIeMEbFHk6YzKKSXeuCqrYfQO0jNBP+kTkvfb+TlshNtIuja7FpSn0K1SscKv9ki+/0VJ4rUanHZCkzNT0f5AVIggEvXp/1nX6Y3oZGMoDtyO4X0GUJuTP7L8OuP/MUAedU4/szTfBN2HHWpdve3dOACF5+DO4kTza1bs8Bbp6vLZ+LXU9jq6faT8J/TQrqjUzUlD32PMTJvaVAkZjJBQi5Ebj0J3B7sRDQL3eZKD41Zpk6ZpIX7xgxZ4evExH1zYIKN55Bpdl5YiA+/P5YlM0mvde8HuIzBKMG4ids9TDkbZ4epgJE6C0BPr/xuJQzcdyfiCHHqb/e6C/VMqcKCUKQWXiMFDZLcKzyf+0EYI8KZR5uJyxwPOZ2y8ufAY9Lcr2oipT2c/qliH22FKs5EP6sqlCEMNXtfWwh+vZNh92hgZlE18ztFDXRFYVPZ6hZz1y8/kfOh0oCypQSsv+In416pWAxmgoefCuSf1mFVJKT9gbIFzvAYtJnUjs9gqMd49z0MuhQz/3NG4B86698jbFwnMvMnPOLgaX1kdlQFRjnWYfkcOOaTB77qKMVXZVvfQw4Ou62QbErzJXtO1UqbzXXYUTK5WasVqabvdxb3TEoByns+tgwqil5ygJMflQJABqcUYKVL7yQtwJub2VI9DKfLGpoVjQR6QQoZE="
  - secure: "CD2FNDY0dLAkLofzbtxp9ie1hC1I9BREd3v7iL1Iai1G0NwY431K9AHrEFBIY3FzjY98MRuCYguQEjMAq9diZz8GCMLGqcwKw0OeetrtLmlPmiNcfVruYD6255K4NlbCGcwPQ5rpLpDALu+clZc+re4fiw5E1zgL9TYvqSDH5IsbKHa015YNPQl5/UX/MveubklofISQo9eP083fzzsVZfhmtdC3OTh83IMMYUTFuPa1cGqngmmsTpn/ufofKtF9rk/6nrn7AKgu8jVp42ydg5442lzxT8aJjHkruiljQmOAMAgBviXv1P8LgIxXh1nsjRlyg/kVNem4vivOy7iaxxMK876ubcc/lbRNpZBIwXTD1ZGN5TAhc5kvmiirgCE7U2bZlzCNbz1LUHpR6O4uIIcJ0/Q7wCDb2OJf9yQ/92XKLVVpRarnbLmFj2NVHtD8QKDK9nc2G/WUaWZmXDaSOCW5BWkNRm8KVUB8adtMwC+oHqjKROwCdwNSP9kO7s/jOhjoUy0XJk7B+ayUbfKU9M9GhITlTBTgKLVXjTGJErt0zOUgxkLifqoF2ypY5jDXRMtTGcpX8V/1mM0jq4KEwYYItyMnj2UZSxguA1rLg6WN3bw/56q0JQQvnTr0/Z88BbEyLMeD99ePHXJxp5ZVeq9ii36dUPaZEVyJTeCmb0k="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
